# Generated by Django 3.1.1 on 2020-10-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='game',
        ),
        migrations.AddField(
            model_name='rating',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.game'),
        ),
    ]
